RegisterServerEvent('Grossiste:BuyItemsByBankMoney')
AddEventHandler('Grossiste:BuyItemsByBankMoney', function(token, thePrice, theItem, s_index, theLabel)
    if not CheckToken(token, source, "Grossiste:BuyItemsByBankMoney") then return end
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)

    if xPlayer.getBank() >= thePrice then
        xPlayer.removeAccountMoney('bank',thePrice)
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~g~Vous avez reçu x"..s_index.." "..theLabel)
        xPlayer.addInventoryItem(theItem, s_index)
    else
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~r~Vous n'avez pas assez d'argent sur votre compte")
	end
end)

RegisterServerEvent('Grossiste:BuyItemsByMoney')
AddEventHandler('Grossiste:BuyItemsByMoney', function(token, thePrice, theItem, s_index, theLabel)
    if not CheckToken(token, source, "Grossiste:BuyItemsByMoney") then return end
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)

    if xPlayer.getMoney() >= thePrice then
        xPlayer.removeMoney(thePrice)
        xPlayer.addInventoryItem(theItem, s_index)
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~g~Vous avez reçu x"..s_index.." "..theLabel)
    else
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~r~Vous n'avez pas assez d'argent sur vous")
	end
end)

RegisterServerEvent('Grossiste:BuyItemsByDirtyMoney')
AddEventHandler('Grossiste:BuyItemsByDirtyMoney', function(token, thePrice, theItem, s_index, theLabel)
    if not CheckToken(token, source, "Grossiste:BuyItemsByByDirtyMoney") then return end
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)

    if xPlayer.getAccount('black_money').money >= thePrice then
        xPlayer.removeAccountMoney('black_money', tonumber(thePrice))
        xPlayer.addInventoryItem(theItem, s_index)
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~g~Vous avez reçu x"..s_index.." "..theLabel)
    else
        TriggerClientEvent('Extasy:showNotification', xPlayer.source, "~r~Vous n'avez pas assez d'argent de source inconnue sur vous")
	end
end)

ESX.RegisterUsableItem('Biere', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('Biere', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu une bière")
end)
ESX.RegisterUsableItem('Whisky', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('Whisky', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu un whisky")
end)
ESX.RegisterUsableItem('rhum', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('rhum', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu un rhum")
end)
ESX.RegisterUsableItem('Gin', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('Gin', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu du Gin")
end)
ESX.RegisterUsableItem('rhum', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('rhum', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu un rhum")
end)
ESX.RegisterUsableItem('Baileys', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('Baileys', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu un Baileys")
end)
ESX.RegisterUsableItem('Eaudevie', function(source)
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
	xPlayer.removeInventoryItem('Eaudevie', 1)
	TriggerClientEvent("Extasy:AddThirst", source, 5)
	TriggerClientEvent('eBasicneeds:onDrink', source)
	TriggerClientEvent('Extasy:UseAlcool', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Tu as bu de l'eau de vie")
end)
ESX.RegisterUsableItem('Chips', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Chips', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un paquet de Chips")
end)
ESX.RegisterUsableItem('cacahuète', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cacahuète', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé des cacahuètes")
end)
ESX.RegisterUsableItem('Chipscrevette', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Chipscrevette', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un paquet de Chips goût crevettes")
end)
ESX.RegisterUsableItem('Gambasbraisees', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Gambasbraisees', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 50)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé des Gambas braisées")
end)
ESX.RegisterUsableItem('Steakfrites', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Steakfrites', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un Steak-Frite")
end)
ESX.RegisterUsableItem('Calmarfrit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Calmarfrit', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un calamar frit")
end)
ESX.RegisterUsableItem('calzone', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('calzone', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un calzone")
end)
ESX.RegisterUsableItem('Glace_vanille', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('Glace_vanille', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé une glace")
end)
ESX.RegisterUsableItem('hotdog', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('hotdog', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé un hotdog")
end)
ESX.RegisterUsableItem('ribs', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('ribs', 1)
	TriggerClientEvent("Extasy:AddHunger", source, 30)	
	TriggerClientEvent('eBasicneeds:onEat', source)
	TriggerClientEvent('Extasy:ShowNotification', source, "Vous avez mangé des ribs")
end)