cfg_org = {}

cfg_org.invCategories = {
	"Aucun",
	"Nourriture / Object",
	"Armes",
}

cfg_org.vehicles = {
	{
		cat_name = "Commercials",
		value = "commercials",
		vehicles = {
			{name = "Benson", hash = "benson", price = 150000, capacity = 120},
			{name = "Biff", hash = "biff", price = 120000, capacity = 100},
			{name = "Mule", hash = "mule", price = 120000, capacity = 100},
			{name = "Mule 2", hash = "mule2", price = 100000, capacity = 100},
			{name = "Mule 3", hash = "mule3", price = 120000, capacity = 100},
			{name = "Taco", hash = "taco", price = 125000, capacity = 45},
			{name = "Stockade", hash = "stockade", price = 100000, capacity = 80},
		},
	},
	{
		cat_name = "Compacts",
		value = "compacts",
		vehicles = {
			{name = "Blista", hash = "blista", price = 8000, capacity = 30},
			{name = "Blista 2", hash = "blista2", price = 17000, capacity = 35},
			{name = "Blista 3", hash = "blista3", price = 22000, capacity = 35},
			{name = "Brioso", hash = "brioso", price = 9000, capacity = 20},
			{name = "Dilettante", hash = "dilettante", price = 7000, capacity = 30},
			{name = "Issi 2", hash = "issi2", price = 10000, capacity = 20},
			{name = "Panto", hash = "panto", price = 6000, capacity = 20},
			{name = "Prairie", hash = "prairie", price = 7500, capacity = 30},
			{name = "Rhapsody", hash = "rhapsody", price = 5500, capacity = 30},
		},
	},
	{
		cat_name = "Coupes",
		value = "coupes",
		vehicles = {
			{name = "Cognoscenti Cabrio", hash = "cogcabrio", price = 80000, capacity = 30},
			{name = "Exemplar", hash = "exemplar", price = 48000, capacity = 30},
			{name = "F620", hash = "f620", price = 60000, capacity = 30},
			{name = "Felon", hash = "felon", price = 72000, capacity = 30},
			{name = "Felon GT", hash = "felon2", price = 82000, capacity = 20},
			{name = "Jackal", hash = "jackal", price = 55000, capacity = 30},
			{name = "Oracle", hash = "oracle", price = 52000, capacity = 30},
			{name = "Oracle XS", hash = "oracle2", price = 60000, capacity = 30},
			{name = "Sentinel", hash = "sentinel", price = 48000, capacity = 30},
			{name = "Sentinel XS", hash = "sentinel2", price = 60000, capacity = 30},
			{name = "Windsor", hash = "windsor", price = 125000, capacity = 30},
			{name = "Windsor Drop", hash = "windsor2", price = 150000, capacity = 20},
			{name = "Zion Cabrio", hash = "zion2", price = 65000, capacity = 20},
		},
	},
	{
		cat_name = "Industriel",
		value = "industriel",
		vehicles = {
			{name = "Guardian", hash = "guardian", price = 100000, capacity = 80},
			{name = "Rubble", hash = "rubble", price = 90000, capacity = 80},
			{name = "Tip Truck", hash = "tiptruck", price = 90000, capacity = 80},
			{name = "Tip Truck 2", hash = "tiptruck2", price = 90000, capacity = 80},
		},
	},
	{
		cat_name = "Imports",
		value = "imports",
		vehicles = {
            {name = "Mercedes GLE2020", hash = "gle53", price = 950000, capacity = 40},
            {name = "Mercedes GT63S AMG", hash = "gt63samg", price = 999000, capacity = 40},
            {name = "KTM EXC 450 Jaune", hash = "2020exc", price = 225000},
            {name = "KTM EXC 450 Orange", hash = "2020exco", price = 225000},
            {name = "Toyota Supra", hash = "supra2", price = 225000},
            {name = "Golf Mk7", hash = "rmodmk7", price = 225000},
            {name = "Porsche Panamera", hash = "pmansory", price = 225000},
            {name = "Raptor 150", hash = "raptor150", price = 225000},
            {name = "Jeep Trackhawk", hash = "rmodjeep", price = 225000},
            {name = "Bentley Mulliner", hash = "rmodbacalar", price = 225000},
            {name = "Unarm", hash = "unarm", price = 225000},
            {name = "Tiger 2", hash = "tiger2", price = 225000},
            {name = "MHX", hash = "mhx", price = 225000},
            {name = "Tampa R", hash = "tampar", price = 225000},
            {name = "Contender C", hash = "contenderc", price = 225000},
            {name = "Buffalo H", hash = "buffaloh", price = 225000},
            {name = "BMW M8 WB", hash = "bmwm8wb", price = 225000},
        },
	},
	{
		cat_name = "Imports GTA",
		value = "imports GTA",
		vehicles = {
			{name = "Jugular", hash = "jugular", price = 600000, capacity = 25},
			{name = "Caracara 2", hash = "caracara2", price = 600000, capacity = 35},
			{name = "Neo", hash = "neo", price = 400000, capacity = 15},
			{name = "Brioso 2", hash = "brioso2", price = 300000, capacity = 15},
			{name = "Weevil", hash = "weevil", price = 250000, capacity = 10},
			{name = "Krieger", hash = "krieger", price = 500000, capacity = 15},
			{name = "Emerus", hash = "emerus", price = 550000, capacity = 15},
			{name = "Itali RSX", hash = "italirsx", price = 550000, capacity = 10},
            {name = "Zorrusso", hash = "zorrusso", price = 500000, capacity = 15},
            {name = "Rebla", hash = "rebla", price = 500000, capacity = 20},
            {name = "Vstr", hash = "vstr", price = 500000, capacity = 20},
            {name = "Komoda", hash = "komoda", price = 500000, capacity = 20},
        },
	},
	{
		cat_name = "Moto",
		value = "moto",
		vehicles = {
			{name = "Akuma", hash = "akuma", price = 15000},
			{name = "Avarus", hash = "avarus", price = 27000},
			{name = "Bagger", hash = "bagger", price = 20000},
			{name = "Bati 801", hash = "bati", price = 20000},
			{name = "Bati 801 RR", hash = "bati2", price = 30000},
			{name = "BF 400", hash = "bf400", price = 10000},
			{name = "Carbon RS", hash = "carbonrs", price = 55000},
			{name = "Chimera", hash = "chimera", price = 14000},
			{name = "Cliffhanger", hash = "cliffhanger", price = 27000},
			{name = "Daemon", hash = "daemon", price = 17000},
			{name = "Daemon High", hash = "Daemon2", price = 20000},
			{name = "Defiler", hash = "defiler", price = 14000},
			{name = "Deathbike", hash = "deathbike", price = 19000},
			{name = "Diablous", hash = "diablous", price = 25000},
			{name = "Diablous 2", hash = "diablous2", price = 35000},
			{name = "Double", hash = "double", price = 40000},
			{name = "Enduro", hash = "enduro", price = 8000},
			{name = "Esskey", hash = "esskey", price = 6000},
			{name = "Faggio", hash = "faggio", price = 2800},
			{name = "Faggio 2", hash = "faggio2", price = 2800},
			{name = "Faggio 3", hash = "faggio3", price = 2800},
			{name = "FCR", hash = "fcr", price = 25000},
			{name = "FCR 2", hash = "fcr2", price = 35000},
			{name = "Gargoyle", hash = "gargoyle", price = 24000},
			{name = "Hakuchou", hash = "hakuchou", price = 45000},
			{name = "Hakuchou Sport", hash = "hakuchou2", price = 65000},
			{name = "Hexer", hash = "hexer", price = 18000},
			{name = "Innovation", hash = "innovation", price = 32000},
			{name = "Lectro", hash = "lectro", price = 55000},
			{name = "Manchez", hash = "manchez", price = 10600},
			{name = "Nemesis", hash = "nemesis", price = 8500},
			{name = "Nightblade", hash = "nightblade", price = 50000},
			{name = "PCJ 600", hash = "pcj", price = 9000},
			{name = "Ratbike", hash = "ratbike", price = 20000},
			{name = "Ruffian", hash = "ruffian", price = 10000},
			{name = "Sanchez", hash = "sanchez", price = 10600},
			{name = "Sanchez Sport", hash = "sanchez2", price = 10600},
			{name = "Sanctus", hash = "sanctus", price = 50000},
			{name = "Shotaro", hash = "shotaro", price = 150000},
			{name = "Sovereign", hash = "sovereign", price = 32000},
			{name = "Thrust", hash = "thrust", price = 35000},
			{name = "Vader", hash = "vader", price = 10000},
			{name = "Vortex", hash = "vortex", price = 14000},
			{name = "Wolfsbane", hash = "wolfsbane", price = 13000},
			{name = "Zombie ", hash = "zombiea", price = 14000},
			{name = "Zombie Luxuary", hash = "zombieb", price = 18000},
		},
	},
	{
		cat_name = "Muscle",
		value = "muscle",
		vehicles = {
			{name = "Blade", hash = "blade", price = 22000, capacity = 30},	
			{name = "Buccaneer", hash = "buccaneer", price = 27000, capacity = 20},
			{name = "Buccaneer Rider", hash = "buccaneer2", price = 36000, capacity = 20},
			{name = "Chino", hash = "chino", price = 22000, capacity = 20},
			{name = "Chino Luxe", hash = "chino2", price = 28000, capacity = 20},
			{name = "Clique", hash = "clique", price = 25000, capacity = 30},
			{name = "Coquette 3", hash = "coquette3", price = 80000, capacity = 30},
			{name = "Deviant", hash = "deviant", price = 55000, capacity = 20},
			{name = "Dominator", hash = "dominator", price = 50000, capacity = 30},
			{name = "Dominator GT", hash = "dominator2", price = 63000, capacity = 30},
			{name = "Dominator GTX", hash = "Dominator3", price = 65000, capacity = 30},
			{name = "Dukes", hash = "dukes", price = 41000, capacity = 20},
			{name = "Faction", hash = "faction", price = 30000, capacity = 30},
			{name = "Faction Rider", hash = "faction2", price = 45000, capacity = 30},
			{name = "Faction XL", hash = "faction3", price = 60000, capacity = 30},
			{name = "Ellie", hash = "ellie", price = 35000, capacity = 30},
			{name = "Gauntlet", hash = "gauntlet", price = 42000, capacity = 30},
			{name = "Hermes", hash = "hermes", price = 85000, capacity = 20},
			{name = "Hotknife", hash = "hotknife", price = 150000, capacity = 20},
			{name = "Hustler", hash = "hustler", price = 100000, capacity = 20},
			{name = "Impaler", hash = "impaler", price = 25000, capacity = 30},
			{name = "Impaler 2", hash = "impaler2", price = 30000, capacity = 30},
			{name = "Impaler 3", hash = "impaler3", price = 35000, capacity = 30},
			{name = "Imperator", hash = "imperator", price = 45000, capacity = 30},
			{name = "Moonbeam", hash = "moonbeam", price = 65000, capacity = 50},
			{name = "Moonbeam Rider", hash = "moonbeam2", price = 75000, capacity = 50},
			{name = "Nightshade", hash = "nightshade", price = 95000, capacity = 30},
			{name = "Peyote 2", hash = "peyote2", price = 85000, capacity = 40},
			{name = "Phoenix", hash = "phoenix", price = 25000, capacity = 30},
			{name = "Picador", hash = "picador", price = 27000, capacity = 50},
			{name = "Ratloader", hash = "ratloader", price = 35000, capacity = 30},
			{name = "Ratloader 2", hash = "ratloader2", price = 50000, capacity = 50},
			{name = "Ruiner", hash = "ruiner", price = 29000, capacity = 40},
			{name = "Sabre GT", hash = "sabregt", price = 37000, capacity = 30},
			{name = "Sabre Turbo", hash = "sabregt2", price = 35000, capacity = 30},
			{name = "Slamvan", hash = "slamvan", price = 20000, capacity = 50},
			{name = "Slamvan 2", hash = "slamvan2", price = 22000, capacity = 50},
			{name = "Slamvan 3", hash = "slamvan3", price = 27500, capacity = 50},
			{name = "Stalion", hash = "stalion", price = 37000, capacity = 30},
			{name = "Tampa", hash = "tampa", price = 35000, capacity = 20},
			{name = "Tulip", hash = "tulip", price = 37500, capacity = 30},
			{name = "Vamos", hash = "vamos", price = 42500, capacity = 30},
			{name = "Vigero", hash = "vigero", price = 18000, capacity = 30},
			{name = "Virgo", hash = "virgo", price = 20000, capacity = 40},
			{name = "Virgo 2", hash = "virgo2", price = 29000, capacity = 40},
			{name = "Virgo 3", hash = "virgo3", price = 39000, capacity = 40},
			{name = "Voodoo", hash = "voodoo", price = 20000, capacity = 30},
			{name = "Voodoo 2", hash = "voodoo2", price = 14000, capacity = 30},
			{name = "Yosemite", hash = "yosemite", price = 50000, capacity = 50},
		},
	},
	{
		cat_name = "Off-Road",
		value = "offroad",
		vehicles = {
			{name = "BF Injection", hash = "bfinjection", price = 24000, capacity = 20},
			{name = "Bifta", hash = "bifta", price = 30000, capacity = 20},
			{name = "Blazer", hash = "blazer", price = 15000},
			{name = "Blazer 3", hash = "blazer3", price = 17500},
			{name = "Blazer 4", hash = "blazer4", price = 25000},
			{name = "Bodhi 2", hash = "bodhi2", price = 75000, capacity = 50},
			{name = "Brawler", hash = "brawler", price = 65000, capacity = 30},
			{name = "Brutus", hash = "brutus", price = 150000, capacity = 60},
			{name = "Duneloader", hash = "dloader", price = 55000, capacity = 40},
			{name = "Dubsta 3", hash = "dubsta3", price = 150000, capacity = 80},
			{name = "Dune", hash = "dune", price = 15000, capacity = 20},
			{name = "Freecrawler", hash = "freecrawler", price = 75000, capacity = 50},
			{name = "Kalahari", hash = "kalahari", price = 55000, capacity = 45},
			{name = "Kamacho", hash = "kamacho", price = 200000, capacity = 80},
			{name = "Mesa Trail", hash = "mesa3", price = 75000, capacity = 50},
			{name = "Rancher XL", hash = "rancherxl", price = 80000, capacity = 50},
			{name = "Rebel", hash = "rebel", price = 50000, capacity = 50},
			{name = "Rebel 2", hash = "rebel2", price = 65000, capacity = 50},
			{name = "Riata", hash = "riata", price = 85000, capacity = 50},
			{name = "Sandking", hash = "sandking", price = 150000, capacity = 80},
			{name = "Sandking2", hash = "sandking2", price = 200000, capacity = 80},
			{name = "Trophy Truck", hash = "trophytruck", price = 85000, capacity =20 },
			{name = "Trophy Truck 2", hash = "trophytruck2", price = 100000, capacity = 20},
            {name = "Winky", hash = "winky", price = 100000, capacity = 20},
		},
	},
	{
		cat_name = "SUVs",
		value = "suvs",
		vehicles = {
			{name = "Baller", hash = "baller", price = 65000, capacity = 40},
			{name = "Baller 2", hash = "baller2", price = 95000, capacity = 50},
			{name = "Baller Sport", hash = "baller3", price = 125000, capacity = 40},
			{name = "Baller Sport 2", hash = "baller4", price = 135000, capacity = 50},
			{name = "BJ XL", hash = "bjxl", price = 115000, capacity = 50},	
			{name = "Cavalcade", hash = "cavalcade", price = 60000, capacity = 50},
			{name = "Cavalcade 2", hash = "cavalcade2", price = 75000, capacity = 50},
			{name = "Contender", hash = "contender", price = 150000, capacity = 60},
			{name = "Dubsta", hash = "dubsta", price = 65000, capacity = 55},
			{name = "Dubsta Luxuary", hash = "dubsta2", price = 75000, capacity = 55},
			{name = "FQ2", hash = "fq2", price = 50000, capacity = 40},
			{name = "Granger", hash = "granger", price = 100000, capacity = 50},
			{name = "Gresley", hash = "gresley", price = 55000, capacity = 40},
			{name = "Habanero", hash = "habanero", price = 50000, capacity = 40},
			{name = "Huntley", hash = "huntley", price = 75000, capacity = 40},
			{name = "Landstalker", hash = "landstalker", price = 65000, capacity = 45},
			{name = "Mesa", hash = "mesa", price = 35000, capacity = 55},
			{name = "Patriot", hash = "patriot", price = 200000, capacity = 40},
			{name = "Patriot 2", hash = "patriot2", price = 500000, capacity = 40},
			{name = "Radius", hash = "radi", price = 50000, capacity = 40},
			{name = "Rocoto", hash = "rocoto", price = 85000, capacity = 40},
			{name = "Seminole", hash = "seminole", price = 50000, capacity = 40},
			{name = "Toros", hash = "toros", price = 100000, capacity = 40},
			{name = "XLS", hash = "xls", price = 85000, capacity = 40},
		},
	},
	{
		cat_name = "Sedans",
		value = "sedans",
		vehicles = {
			{name = "Asea", hash = "asea", price = 15000, capacity = 35},
			{name = "Asterope", hash = "asterope", price = 17500, capacity = 35},
			{name = "Cognoscenti", hash = "cognoscenti", price = 70000, capacity = 35},
			{name = "Emperor", hash = "emperor", price = 17000, capacity = 30},
			{name = "Fugitive", hash = "fugitive", price = 20000, capacity = 35},
			{name = "Glendale", hash = "glendale", price = 13000, capacity = 35},
			{name = "ingot", hash = "ingot", price = 17000, capacity = 40},
			{name = "Intruder", hash = "intruder", price = 15000, capacity = 35},
			{name = "Premier", hash = "premier", price = 16000, capacity = 35},
			{name = "Primo", hash = "primo", price = 20000, capacity = 35},
			{name = "Primo Custom", hash = "primo2", price = 25000, capacity = 35},
			{name = "Regina", hash = "regina", price = 13000, capacity = 40},
			{name = "Stafford", hash = "stafford", price = 17500, capacity = 35},
			{name = "Stanier", hash = "stanier", price = 15000, capacity = 35},
			{name = "Stratum", hash = "stratum", price = 16000, capacity = 40},
			{name = "Stretch", hash = "stretch", price = 300000, capacity = 35},
			{name = "Super Diamond", hash = "superd", price = 200000, capacity = 35},
			{name = "Surge", hash = "surge", price = 17500, capacity = 35},
			{name = "Tailgater", hash = "tailgater", price = 38000, capacity = 35},
			{name = "Warrener", hash = "warrener", price = 15000, capacity = 35},
			{name = "Washington", hash = "washington", price = 13500, capacity = 35},
		},
	},
	{
		cat_name = "Sports",
		value = "sports",
		vehicles = {
			{name = "Alpha", hash = "alpha", price = 90000, capacity = 35},
			{name = "Banshee", hash = "banshee", price = 100000, capacity = 35},
			{name = "Bestia GTS", hash = "bestiagts", price = 110000, capacity = 35},
			{name = "Buffalo", hash = "buffalo", price = 35000, capacity = 35},
			{name = "Buffalo 2", hash = "buffalo2", price = 45000, capacity = 35},
			{name = "Buffalo 3", hash = "buffalo3", price = 40000, capacity = 35},
			{name = "Carbonizzare", hash = "carbonizzare", price = 110000, capacity = 20},
			{name = "Comet 2", hash = "comet2", price = 95000, capacity = 35},
			{name = "Comet 3", hash = "comet3", price = 97500, capacity = 35},
			{name = "Comet 4", hash = "comet4", price = 90000, capacity = 35},
			{name = "Comet 5", hash = "comet5", price = 115000, capacity = 35},
			{name = "Coquette", hash = "coquette", price = 95000, capacity = 35},
			{name = "Deveste", hash = "deveste", price = 135000, capacity = 20},
			{name = "Elegy", hash = "elegy", price = 95000, capacity = 35},
			{name = "Elegy 2", hash = "elegy2", price = 90000, capacity = 35},
			{name = "Feltzer 2", hash = "feltzer2", price = 85000, capacity = 35},
			{name = "Flash GT", hash = "flashgt", price = 70000, capacity = 35},
			{name = "Furore GT", hash = "furoregt", price = 70000, capacity = 35},
			{name = "Fusilade", hash = "fusilade", price = 60000, capacity = 35},
			{name = "Futo", hash = "futo", price = 55000, capacity = 35},
			{name = "GB200", hash = "gb200", price = 65000, capacity = 35},
			{name = "Hotring", hash = "hotring", price = 60000, capacity = 35},
			{name = "Itali GTO", hash = "italigto", price = 90000, capacity = 20},
			{name = "Jester", hash = "jester", price = 70000, capacity = 25},
			{name = "Jester 2", hash = "jester2", price = 60000, capacity = 25},
			{name = "Jester 3", hash = "jester3", price = 75000, capacity = 25},
			{name = "Khamelion", hash = "khamelion", price = 80000, capacity = 35},
			{name = "Kuruma", hash = "kuruma", price = 65000, capacity = 35},
			{name = "Lynx", hash = "lynx", price = 85000, capacity = 30},
			{name = "Massacro", hash = "massacro", price = 75000, capacity = 30},
			{name = "Massacro Racecar", hash = "massacro2", price = 70000, capacity = 30},
			{name = "Neon", hash = "neon", price = 95000, capacity = 35},
			{name = "9F", hash = "ninef", price = 90000, capacity = 30},
			{name = "9F Cabrio", hash = "ninef2", price = 95000, capacity = 30},
			{name = "Omnis", hash = "omnis", price = 55000, capacity = 25},
			{name = "Pariah", hash = "pariah", price = 90000, capacity = 30},
			{name = "Penumbra", hash = "penumbra", price = 65000, capacity = 30},
			{name = "Raiden", hash = "raiden", price = 75000, capacity = 30},
			{name = "Rapid GT", hash = "rapidgt", price = 70000, capacity = 30},
			{name = "Rapid GT 2", hash = "rapidgt2", price = 75000, capacity = 30},
			{name = "Raptor", hash = "raptor", price = 60000, capacity = 20},
			{name = "Ruston", hash = "ruston", price = 60000, capacity = 20},
			{name = "Schafter 2", hash = "schafter2", price = 55000, capacity = 35},
			{name = "Schafter 3", hash = "schafter3", price = 60000, capacity = 35},
			{name = "Schafter 4", hash = "schafter4", price = 70000, capacity = 35},
			{name = "Schlagen", hash = "schlagen", price = 115000, capacity = 35},
			{name = "Schwarzer", hash = "schwarzer", price = 65000, capacity = 35},
			{name = "Sentinel 3", hash = "sentinel3", price = 85000, capacity = 30},
			{name = "Seven 70", hash = "seven70", price = 75000, capacity = 30},
			{name = "Specter", hash = "specter", price = 65000, capacity = 35},
			{name = "Specter 2", hash = "specter2", price = 70000, capacity = 35},
			{name = "Streiter", hash = "streiter", price = 60000, capacity = 40},
			{name = "Sultan", hash = "sultan", price = 35000, capacity = 35},
			{name = "Sultan 2", hash = "sultan2", price = 40000, capacity = 35},
			{name = "Surano", hash = "surano", price = 65000, capacity = 35},
			{name = "Tampa 2", hash = "tampa2", price = 55000, capacity = 35},
			{name = "Tropos", hash = "tropos", price = 60000, capacity = 35},
			{name = "Verlierer 2", hash = "verlierer2", price = 65000, capacity = 25},
		},
	},
	{
		cat_name = "Classic Sport",
		value = "classic_sport",
		vehicles = {
			{name = "Btype", hash = "btype", price = 125000, capacity = 30},
			{name = "B-Type Hotroad", hash = "btype2", price = 150000, capacity = 30},
			{name = "B-Type Luxe", hash = "btype3", price = 175000, capacity = 30},
			{name = "Casco", hash = "casco", price = 45000, capacity = 35},
			{name = "Cheetah 2", hash = "cheetah2", price = 200000, capacity = 30},
			{name = "Coquette 2", hash = "coquette2", price = 75000, capacity = 30},
			{name = "Fagaloa", hash = "fagaloa", price = 40000, capacity = 35},
			{name = "Feltzer 3", hash = "feltzer3", price = 50000, capacity = 30},
			{name = "GT500", hash = "gt500", price = 45000, capacity = 30},
			{name = "Infernus 2", hash = "infernus2", price = 42500, capacity = 30},
			{name = "Mamba", hash = "mamba", price = 40000, capacity = 30},
			{name = "Manana", hash = "manana", price = 25000, capacity = 25},
			{name = "Michelli", hash = "michelli", price = 20000, capacity = 30},
			{name = "Monroe", hash = "monroe", price = 65000, capacity = 30},
			{name = "Pigalle", hash = "pigalle", price = 30000, capacity = 35},
			{name = "Rapid GT 3", hash = "rapidgt3", price = 85000, capacity = 30},
			{name = "Retinue", hash = "retinue", price = 25000, capacity = 30},
			{name = "Stinger", hash = "stinger", price = 110000, capacity = 30},
			{name = "Stinger GT", hash = "stingergt", price = 120000, capacity = 30},
			{name = "Swinger", hash = "swinger", price = 80000, capacity = 25},
			{name = "Torero", hash = "torero", price = 75000, capacity = 25},
			{name = "Tornado", hash = "tornado", price = 35000, capacity = 35},
			{name = "Tornado 2", hash = "tornado2", price = 37500, capacity = 35},
			{name = "Tornado 3", hash = "tornado3", price = 30000, capacity = 35},
			{name = "Tornado 4", hash = "tornado4", price = 32500, capacity = 35},
			{name = "Tornado 5", hash = "tornado5", price = 40000, capacity = 30},
			{name = "Tornado 6", hash = "tornado6", price = 35000, capacity = 35},
			{name = "Turismo 2", hash = "turismo2", price = 80000, capacity = 30},
			{name = "Z190", hash = "z190", price = 75000, capacity = 30},
			{name = "Z-Type", hash = "ztype", price = 115000, capacity = 25},
			{name = "Cheburek", hash = "cheburek", price = 35000, capacity = 30},
		},
		
	},
	{
		cat_name = "Super",
		value = "super",
		vehicles = {
			{name = "Adder", hash = "adder", price = 450000, capacity = 25},
			{name = "Autarch", hash = "autarch", price = 350000, capacity = 25},
			{name = "Banshee 2", hash = "banshee2", price = 370000, capacity = 25},
			{name = "Bullet", hash = "bullet", price = 150000, capacity = 25},
			{name = "Cheetah", hash = "cheetah", price = 375000, capacity = 25},
			{name = "Cyclone", hash = "cyclone", price = 180000, capacity = 25},
			{name = "Entity 2", hash = "entity2", price = 375000, capacity = 25},
			{name = "Entity FX", hash = "entityfx", price = 400000, capacity = 25},
			{name = "FMJ", hash = "fmj", price = 275000, capacity = 25},
			{name = "Infernus", hash = "infernus", price = 225000, capacity = 25},
			{name = "Itali GTB", hash = "italigtb", price = 325000, capacity = 25},
			{name = "Itali GTB 2", hash = "italigtb2", price = 350000, capacity = 25},
			{name = "LE7B", hash = "le7b", price = 225000, capacity = 25},
			{name = "Nero", hash = "nero", price = 400000, capacity = 25},
			{name = "Nero 2", hash = "nero2", price = 425000, capacity = 25},
			{name = "Osiris", hash = "osiris", price = 375000, capacity = 25},
			{name = "Penetrator", hash = "penetrator", price = 225000, capacity = 25},
			{name = "PFister811", hash = "pfister811", price = 300000, capacity = 25},
			{name = "Prototipo", hash = "prototipo", price = 425000, capacity = 25},
			{name = "Reaper", hash = "reaper", price = 325000, capacity = 25},
			{name = "SC1", hash = "sc1", price = 300000, capacity = 35},
			{name = "Sheava", hash = "sheava", price = 275000, capacity = 35},
			{name = "Sultan RS", hash = "sultanrs", price = 150000, capacity = 35},
			{name = "T20", hash = "t20", price = 250000, capacity = 35},
			{name = "Taipan", hash = "taipan", price = 325000, capacity = 35},
			{name = "Tempesta", hash = "tempesta", price = 300000, capacity = 35},
			{name = "Tezeract", hash = "tezeract", price = 425000, capacity = 35},
			{name = "Turismo R", hash = "turismor", price = 325000, capacity = 35},
			{name = "Tyran T", hash = "tyrant", price = 375000, capacity = 35},
			{name = "Tyrus", hash = "tyrus", price = 275000, capacity = 35},
			{name = "Vacca", hash = "vacca", price = 325000, capacity = 35},
			{name = "Vagner", hash = "vagner", price = 275000, capacity = 35},
			{name = "Visione", hash = "visione", price = 325000, capacity = 35},
			{name = "Voltic", hash = "voltic", price = 300000, capacity = 35},
			{name = "XA21", hash = "xa21", price = 350000, capacity = 35},
			{name = "Zentorno", hash = "zentorno", price = 375000, capacity = 35},
		},
	},
	{
		cat_name = "Utility",
		value = "utility",
		vehicles = {
			{name = "Sadler", hash = "sadler", price = 75000, capacity = 50},
			{name = "Scrap", hash = "scrap", price = 60000, capacity = 50},
			{name = "Towtruck", hash = "towtruck", price = 50000, capacity = 35},
			{name = "Towtruck 2", hash = "towtruck2", price = 60000, capacity = 30},
			{name = "Tractor", hash = "tractor", price = 60000, capacity = 30},
			{name = "Tractor 2", hash = "tractor2", price = 60000, capacity = 30},
			{name = "Barracks", hash = "barracks", price = 60000, capacity = 30},
			{name = "Barracks 2", hash = "barracks2", price = 60000, capacity = 30},
			{name = "Barracks 3", hash = "barracks3", price = 60000, capacity = 30},
		},
	},
	{
		cat_name = "Vans",
		value = "vans",
		vehicles = {
			{name = "Bison", hash = "bison", price = 65000, capacity = 45},	
			{name = "Bison 2", hash = "bison2", price = 70000, capacity = 45},
			{name = "Bison 3", hash = "bison3", price = 75000, capacity = 45},
			{name = "Bobcat XL", hash = "bobcatxl", price = 50000, capacity = 45},
			{name = "Burrito", hash = "burrito", price = 40000, capacity = 50},
			{name = "Burrito 2", hash = "burrito2", price = 42500, capacity = 50},
			{name = "Burrito 3", hash = "burrito3", price = 45000, capacity = 50},
			{name = "Burrito 4", hash = "burrito4", price = 42500, capacity = 50},
			{name = "Camper", hash = "camper", price = 60000, capacity = 45},
			{name = "Gang Burrito 2", hash = "gburrito2", price = 65000, capacity = 50},
			{name = "Journey", hash = "journey", price = 50000, capacity = 45},
			{name = "Minivan", hash = "minivan", price = 65000, capacity = 40},
			{name = "Minivan 2", hash = "minivan2", price = 70000, capacity = 40},
			{name = "Paradise", hash = "paradise", price = 45000, capacity = 45},
			{name = "Pony", hash = "pony", price = 45000, capacity = 45},
			{name = "Pony 2", hash = "pony2", price = 50000, capacity = 45},
			{name = "Rumpo", hash = "rumpo", price = 60000, capacity = 50},
			{name = "Rumpo 2", hash = "rumpo2", price = 60000, capacity = 50},
			{name = "Rumpo 3", hash = "rumpo3", price = 75000, capacity = 50},
			{name = "Speedo", hash = "speedo", price = 55000, capacity = 50},
			{name = "Speedo 4", hash = "speedo4", price = 60000, capacity = 50},
			{name = "Surfer", hash = "surfer", price = 65000, capacity = 35},
			{name = "Surfer 2", hash = "surfer2", price = 50000, capacity = 35},
			{name = "Youga", hash = "youga", price = 65000, capacity = 50},
			{name = "Youga Luxuary", hash = "youga2", price = 60000, capacity = 50},
		},	
	},
	{
		cat_name = "Velo",
		value = "velo",
		vehicles = {
			{name = "BMX", hash = "bmx", price = 500},
			{name = "Cruiser", hash = "cruiser", price = 500},
			{name = "Fixter", hash = "fixter", price = 750},
			{name = "Scorcher", hash = "scorcher", price = 1000},
			{name = "Tribike", hash = "tribike", price = 1250},
			{name = "Tribike 2", hash = "tribike2", price = 1250},
			{name = "Tribike 3", hash = "tribike3", price = 1250},
		},	
	},
	{
		cat_name = "Hélicoptère",
		value = "helico",
		vehicles = {
			{name = "Cargo Bob", hash = "cargobob", price = 1500500},
		},	
	},
}

cfg_org.colorsList = {
    "Noir métallique",
    "Noir graphite métallisé",
    "Acier métallique noir",
    "Argent foncé métallisé",
    "Argent métallisé",
    "Acier bleu métallisé",
    "Gris acier métallisé",
    "Argent sombre métallique",
    "Argent pierre métallique",
    "Argent nocturne métallisé",
    "Argent béton métallisé",
    "Gris anthracite métallique",
    "Noir mat",
    "Gris mat",
    "Gris clair mat",
    "Noir",
    "Noir Poly",
    "Argent foncé",
    "Argent",
    "Gris béton",
    "Argent nocturne",
    "Noir usé",
    "Graphite usé",
    "Gris argent usé",
    "Argent usé",
    "Bleu argent usé",
    "Argent nocturne usé",
    "Rouge métallique",
    "Rouge torino métallisé",
    "Rouge formula métallisé",
    "Rouge flamme métallisé",
    "Rouge gracieux métallisé",
    "Rouge grenat métallisé",
    "Rouge solaire métallisé",
    "Rouge cabernet métallisé",
    "Rouge fraise métallisé",
    "Orange profond métallisé",
    "Or métallisé",
    "Orange métallisé",
    "Rouge mat",
    "Rouge foncé mat",
    "Orange mat",
    "Jaune Mat",
    "Rouge",
    "Rouge clair",
    "Rouge grenat",
    "Rouge usé",
    "Rouge doré usé",
    "Rouge sang usé",
    "Vert foncé métallisé",
    "Vert racing métallisé",
    "Vert marin métallisé",
    "Vert olive métallisé",
    "Vert clair métallisé",
    "Vert pétrole métallisé",
    "Vert lime mat",
    "Vert foncé",
    "Vert",
    "Vert foncé usé",
    "Vert usé",
    "Vert marin usé",
    "Bleu nocturne métallisé",
    "Bleu foncé métallisé",
    "Bleu cobalt métallisé",
    "Bleu métallisé",
    "Bleu ciel métallisé",
    "Bleu ardoise métallisé",
    "Bleu diamant métallisé",
    "Bleu écume métallisé",
    "Bleu nautique métallisé",
    "Bleu ultra métallisé",
    "Mauve schafter métallisé",
    "Mauve Spinnaker métallisé",
    "Bleu racing métallisé",
    "Bleu clair métallisé",
    "Bleu foncé",
    "Bleu nocturne",
    "Bleu écume",
    "Bleu éclair",
    "Bleu ciel",
    "Bleu clair",
    "Bleu foncé mat",
    "Bleu mat",
    "Bleu nocturne mat",
    "Bleu foncé usé",
    "Bleu usé",
    "Bleu éclair usé",
    "Jaune métallisé",
    "Jaune racing métallisé",
    "Bronze métallisé",
    "Jaune pâle métallisé",
    "Vert lime métallisé",
    "Brun paille métallisé",
    "Brun érable métallisé",
    "Bun beige métallisé",
    "Chocolat métallisé",
    "Brun feltzer métallisé",
    "Beige métallisé",
    "Brun paille métallisé",
    "Brun vert métallisé",
    "Brun bison métallisé",
    "Brun hêtre métallisé",
    "Brun cannelle métallisé",
    "Marron clair métallisé",
    "Brun sable métallisé",
    "Beige clair métallisé",
    "Crème métallisé",
    "Brun",
    "Brun moyen",
    "Brun clair",
    "Blanc métallisé",
    "Blanc froid métallisé",
    "Beige clair usé",
    "Brun usé",
    "Brun foncé usé",
    "Brun paille usé",
    "Acier brossé",
    "Acier noir brossé",
    "Aluminium brossé",
    "Chrome",
    "Blanc cassé usé",
    "Blanc cassé",
    "Orange usé",
    "Orange clair usé",
    "Vert securité métallisé",
    "Jaune usé",
    "Bleu police",
    "Vert mat",
    "Brun mat",
    "Orange pâle usé",
    "Blanc mat",
    "Blanc usé",
    "Vert olive armée usé",
    "Blanc pur",
    "Rose vif",
    "Rose saumon",
    "Rose pfister métallisé",
    "Orange",
    "Vert",
    "Bleu",
    "Bleu foncé métallisé",
    "Mauve foncé métallisé",
    "Rouge foncé métallisé",
    "Vert chasseur",
    "Mauve métallisé",
    "Bleu foncé V métallisé",
    "Noir modshop",
    "Mauve mat",
    "Mauve foncé mat",
    "Rouge lave métallisé",
    "Vert forêt ùat",
    "Vert olive mat",
    "Brun désert mat",
    "Beige désert mat",
    "Vert feuillage mat",
    "Alliage",
    "Bleu pâle",
    "Or pur",
    "Or brossé",
}

cfg_org.pedList = {
    's_f_y_hooker_01',
    's_f_y_hooker_02',
    's_f_y_hooker_03',
    'csb_stripper_01',
    'csb_stripper_02',
    's_f_y_stripper_01',
    's_f_y_stripper_02',
    's_f_y_stripperlite',
    'a_f_y_topless_01',
    'u_m_y_abner',
    'a_m_m_acult_01',
    'a_m_o_acult_01',
    'a_m_o_acult_02',
    'a_m_y_acult_01',
    'a_m_y_acult_02',
    's_f_y_airhostess_01',
    'u_m_m_aldinapoli',
    'ig_amandatownley',
    's_m_y_ammucity_01',
    'ig_andreas',
    'csb_anita',
    'csb_anton',
    'u_m_y_antonb',
    'ig_ashley',
    's_m_y_autopsy_01',
    's_m_m_autoshop_01',
    's_m_m_autoshop_02',
    'g_m_y_azteca_01',
    'u_m_y_babyd',
    'g_m_y_ballaeast_01',
    'g_m_y_ballaorig_01',
    'g_f_y_ballas_01',
    'csb_ballasog',
    'ig_ballasog',
    'g_m_y_ballasout_01',
    'ig_bankman',
    'u_m_m_bankman',
    's_m_y_barman_01',
    's_f_m_fembarber',
    'ig_barry',
    's_f_y_bartender_01',
    'u_m_y_baygor',
    's_f_y_baywatch_01',
    's_m_y_baywatch_01',
    'a_f_m_beach_01',
    'a_f_y_beach_01',
    'a_m_m_beach_01',
    'a_m_m_beach_02',
    'a_m_o_beach_01',
    'a_m_y_beach_01',
    'a_m_y_beach_02',
    'a_m_y_beach_03',
    'a_m_y_beachvesp_01',
    'a_m_y_beachvesp_02',
    'ig_bestmen',
    'ig_beverly',
    'a_f_m_bevhills_01',
    'a_f_m_bevhills_02',
    'a_f_y_bevhills_01',
    'a_f_y_bevhills_02',
    'a_f_y_bevhills_03',
    'a_f_y_bevhills_04',
    'a_m_m_bevhills_01',
    'a_m_m_bevhills_02',
    'a_m_y_bevhills_01',
    'a_m_y_bevhills_02',
    'u_m_m_bikehire_01',
    'u_f_y_bikerchic',
    's_m_y_blackops_01',
    's_m_y_blackops_02',
    'a_f_m_bodybuild_01',
    's_m_m_bouncer_01',
    'ig_brad',
    'a_m_y_breakdance_01',
    'csb_bride',
    'ig_bride',
    'csb_burgerdrug',
    'u_m_y_burgerdrug_01',
    's_m_y_busboy_01',
    'a_m_y_busicas_01',
    'a_f_m_business_02',
    'a_f_y_business_01',
    'a_f_y_business_02',
    'a_f_y_business_03',
    'a_f_y_business_04',
    'a_m_m_business_01',
    'a_m_y_business_01',
    'a_m_y_business_02',
    'a_m_y_business_03',
    's_m_o_busker_01',
    'csb_car3guy1',
    'ig_car3guy1',
    'csb_car3guy2',
    'ig_car3guy2',
    'ig_casey',
    'csb_chef',
    'ig_chef',
    's_m_y_chef_01',
    's_m_m_chemsec_01',
    'g_m_m_chemwork_01',
    'ig_chengsr',
    'g_m_m_chiboss_01',
    'g_m_m_chicold_01',
    'g_m_m_chigoon_01',
    'g_m_m_chigoon_02',
    'csb_chin_goon',
    'u_m_y_chip',
    'ig_chrisformage',
    's_m_m_ciasec_01',
    'mp_m_claude_01',
    'ig_clay',
    'ig_claypain',
    'csb_cletus',
    'ig_cletus',
    's_m_m_cntrybar_01',
    'u_f_y_comjane',
    's_m_y_construct_01',
    's_m_y_construct_02',
    'u_f_m_corpse_01',
    'u_f_y_corpse_01',
    'u_f_y_corpse_02',
    'csb_customer',
    'a_m_y_cyclist_01',
    'u_m_y_cyclist_01',
    'ig_dale',
    'ig_davenorton',
    's_m_y_dealer_01',
    'csb_denise_friend',
    'ig_denise',
    'ig_devin',
    's_m_y_devinsec_01',
    'a_m_y_dhill_01',
    's_m_m_dockwork_01',
    's_m_y_dockwork_01',
    's_m_m_doctor_01',
    'ig_dom',
    's_m_y_doorman_01',
    'a_f_m_downtown_01',
    'a_m_y_downtown_01',
    'ig_dreyfuss',
    'ig_russiandrunk',
    'ig_drfriedlander',
    's_m_y_dwservice_01',
    's_m_y_dwservice_02',
    'a_f_m_eastsa_01',
    'a_f_m_eastsa_02',
    'a_f_y_eastsa_01',
    'a_f_y_eastsa_02',
    'a_f_y_eastsa_03',
    'a_m_m_eastsa_01',
    'a_m_m_eastsa_02',
    'a_m_y_eastsa_01',
    'a_m_y_eastsa_02',
    'a_f_y_epsilon_01',
    'a_m_y_epsilon_01',
    'a_m_y_epsilon_02',
    'mp_m_exarmy_01',
    'ig_fabien',
    's_f_y_factory_01',
    's_m_y_factory_01',
    'g_m_y_famca_01',
    'mp_m_famdd_01',
    'g_m_y_famdnf_01',
    'g_m_y_famfor_01',
    'g_f_y_families_01',
    'a_m_m_farmer_01',
    'a_f_m_fatbla_01',
    'a_f_m_fatcult_01',
    'a_m_m_fatlatin_01',
    'a_f_m_fatwhite_01',
    'ig_fbisuit_01',
    'u_m_m_fibarchitect',
    'u_m_y_fibmugger_01',
    's_m_m_fiboffice_01',
    's_m_m_fiboffice_02',
    'mp_m_fibsec_01',
    'u_m_m_filmdirector',
    'u_m_o_finguru_01',
    's_m_y_fireman_01',
    'a_f_y_fitness_01',
    'a_f_y_fitness_02',
    'ig_floyd',
    'csb_fos_rep',
    'csb_g',
    's_m_m_gaffer_01',
    'csb_ramp_gang',
    'ig_ramp_gang',
    's_m_y_garbage',
    's_m_m_gardener_01',
    'a_m_y_gay_01',
    'a_m_y_gay_02',
    'a_m_m_genfat_01',
    'a_m_m_genfat_02',
    'a_f_y_genhot_01',
    'a_f_o_genstreet_01',
    'a_m_o_genstreet_01',
    'a_m_y_genstreet_01',
    'a_m_y_genstreet_02',
    's_m_m_gentransport',
    'u_m_m_glenstank_01',
    'a_f_y_golfer_01',
    'a_m_m_golfer_01',
    'a_m_y_golfer_01',
    'u_m_m_griff_01',
    's_m_y_grip_01',
    'csb_groom',
    'ig_groom',
    'csb_grove_str_dlr',
    'u_m_y_guido_01',
    'u_m_y_gunvend_01',
    's_m_m_hairdress_01',
    'csb_hao',
    'ig_hao',
    'a_m_m_hasjew_01',
    'a_m_y_hasjew_01',
    'hc_driver',
    'hc_gunman',
    'hc_hacker',
    'csb_ramp_hic',
    'ig_ramp_hic',
    's_m_m_highsec_01',
    's_m_m_highsec_02',
    'a_f_y_hiker_01',
    'a_m_y_hiker_01',
    'a_m_m_hillbilly_01',
    'a_m_m_hillbilly_02',
    'a_f_y_hippie_01',
    'u_m_y_hippie_01',
    'a_m_y_hippy_01',
    'a_f_y_hipster_01',
    'a_f_y_hipster_02',
    'a_f_y_hipster_03',
    'a_f_y_hipster_04',
    'a_m_y_hipster_01',
    'a_m_y_hipster_02',
    'a_m_y_hipster_03',
    'csb_ramp_hipster',
    'ig_ramp_hipster',
    'u_f_y_hotposh_01',
    'csb_hugh',
    'ig_hunter',
    's_m_y_hwaycop_01',
    'u_m_y_imporage',
    'csb_imran',
    'a_f_o_indian_01',
    'a_f_y_indian_01',
    'a_m_m_indian_01',
    'a_m_y_indian_01',
    'ig_janet',
    'csb_janitor',
    's_m_m_janitor',
    'ig_jay_norris',
    'u_m_m_jesus_01',
    'a_m_y_jetski_01',
    'ig_jewelass',
    'u_f_y_jewelass_01',
    'u_m_m_jewelsec_01',
    'u_m_m_jewelthief',
    'ig_jimmyboston',
    'ig_jimmydisanto',
    'ig_joeminuteman',
    'ig_johnnyklebitz',
    'ig_josef',
    'ig_josh',
    'a_f_y_juggalo_01',
    'a_m_y_juggalo_01',
    'u_m_y_justin',
    'ig_kerrymcintosh',
    'g_m_m_korboss_01',
    'g_m_y_korean_01',
    'g_m_y_korean_02',
    'g_m_y_korlieut_01',
    'a_f_m_ktown_01',
    'a_f_m_ktown_02',
    'a_f_o_ktown_01',
    'a_m_m_ktown_01',
    'a_m_o_ktown_01',
    'a_m_y_ktown_01',
    'a_m_y_ktown_02',
    'ig_lamardavis',
    's_m_m_lathandy_01',
    'a_m_y_latino_01',
    'ig_lazlow',
    'ig_lestercrest',
    'ig_lifeinvad_01',
    'ig_lifeinvad_02',
    's_m_m_lifeinvad_01',
    's_m_m_linecook',
    'g_f_y_lost_01',
    'g_m_y_lost_01',
    'g_m_y_lost_02',
    'g_m_y_lost_03',
    's_m_m_lsmetro_01',
    'ig_magenta',
    's_f_m_maid_01',
    'a_m_m_malibu_01',
    'u_m_y_mani',
    'ig_manuel',
    's_m_m_mariachi_01',
    'csb_ramp_marine',
    's_m_m_marine_01',
    's_m_m_marine_02',
    's_m_y_marine_01',
    's_m_y_marine_02',
    's_m_y_marine_03',
    'u_m_m_markfost',
    'ig_marnie',
    'mp_m_marston_01',
    'ig_maryann',
    'csb_maude',
    'ig_maude',
    'a_m_y_methhead_01',
    'csb_ramp_mex',
    'ig_ramp_mex',
    'g_m_m_mexboss_01',
    'g_m_m_mexboss_02',
    'a_m_m_mexcntry_01',
    'g_m_y_mexgang_01',
    'g_m_y_mexgoon_01',
    'g_m_y_mexgoon_02',
    'g_m_y_mexgoon_03',
    'a_m_m_mexlabor_01',
    'a_m_y_mexthug_01',
    'ig_michelle',
    's_f_y_migrant_01',
    's_m_m_migrant_01',
    'u_m_y_militarybum',
    'ig_milton',
    's_m_y_mime',
    'u_f_m_miranda',
    'u_f_y_mistress',
    'mp_f_misty_01',
    'ig_molly',
    'a_m_y_motox_01',
    'a_m_y_motox_02',
    'u_f_o_moviestar',
    's_f_y_movprem_01',
    's_m_m_movprem_01',
    's_m_m_movspace_01',
    'ig_mrk',
    'ig_mrs_thornhill',
    'ig_mrsphillips',
    'a_m_y_musclbeac_01',
    'a_m_y_musclbeac_02',
    'csb_mweather',
    'ig_natalia',
    'ig_nervousron',
    'ig_nigel',
    'a_m_m_afriamer_01',
    'mp_m_niko_01',
    'a_m_m_og_boss_01',
    'ig_old_man1a',
    'ig_old_man2',
    'ig_omega',
    'ig_oneil',
    'ig_orleans',
    'csb_ortega',
    'ig_ortega',
    'csb_oscar',
    'a_m_m_paparazzi_01',
    'u_m_y_paparazzi',
    'ig_paper',
    's_m_m_paramedic_01',
    'u_m_y_party_01',
    'u_m_m_partytarget',
    'ig_patricia',
    's_m_y_pestcont_01',
    's_m_m_pilot_01',
    's_m_m_pilot_02',
    's_m_y_pilot_01',
    'u_m_y_pogo_01',
    'g_m_y_pologoon_01',
    'g_m_y_pologoon_02',
    'a_m_m_polynesian_01',
    'a_m_y_polynesian_01',
    'u_f_y_poppymich',
    'csb_porndudes',
    's_m_m_postal_01',
    's_m_m_postal_02',
    'ig_priest',
    'u_f_y_princess',
    's_m_m_prisguard_01',
    's_m_y_prismuscl_01',
    's_m_y_prisoner_01',
    'u_m_y_proldriver_01',
    'a_f_m_prolhost_01',
    'a_m_m_prolhost_01',
    'u_f_o_prolhost_01',
    'csb_prologuedriver',
    'csb_prolsec',
    'ig_prolsec_02',
    'u_m_m_prolsec_01',
    'u_f_m_promourn_01',
    'u_m_m_promourn_01',
    'mp_g_m_pros_01',
    's_f_y_ranger_01',
    's_m_y_ranger_01',
    'csb_reporter',
    'u_m_m_rivalpap',
    'a_m_y_roadcyc_01',
    's_m_y_robber_01',
    'csb_roccopelosi',
    'ig_roccopelosi',
    'u_m_y_rsranger_01',
    'a_f_y_runner_01',
    'a_m_y_runner_01',
    'a_m_y_runner_02',
    'a_f_y_rurmeth_01',
    'a_m_m_rurmeth_01',
    'a_f_m_salton_01',
    'a_f_o_salton_01',
    'a_m_m_salton_01',
    'a_m_m_salton_02',
    'a_m_m_salton_03',
    'a_m_m_salton_04',
    'a_m_o_salton_01',
    'a_m_y_salton_01',
    'g_m_y_salvaboss_01',
    'g_m_y_salvagoon_01',
    'g_m_y_salvagoon_02',
    'g_m_y_salvagoon_03',
    'u_m_y_sbike',
    'a_f_y_scdressy_01',
    's_m_m_scientist_01',
    'csb_screen_writer',
    'ig_screen_writer',
    's_f_y_scrubs_01',
    's_m_m_security_01',
    's_f_m_shop_high',
    's_f_y_shop_low',
    's_m_y_shop_mask',
    's_f_y_shop_mid',
    'mp_m_shopkeep_01',
    'ig_siemonyetarian',
    'a_f_y_skater_01',
    'a_m_m_skater_01',
    'a_m_y_skater_01',
    'a_m_y_skater_02',
    'a_f_m_skidrow_01',
    'a_m_m_skidrow_01',
    's_m_m_snowcop_01',
    'a_m_m_socenlat_01',
    'ig_solomon',
    'a_f_m_soucent_01',
    'a_f_m_soucent_02',
    'a_f_o_soucent_01',
    'a_f_o_soucent_02',
    'a_f_y_soucent_01',
    'a_f_y_soucent_02',
    'a_f_y_soucent_03',
    'a_m_m_soucent_01',
    'a_m_m_soucent_02',
    'a_m_m_soucent_03',
    'a_m_m_soucent_04',
    'a_m_o_soucent_01',
    'a_m_o_soucent_02',
    'a_m_o_soucent_03',
    'a_m_y_soucent_01',
    'a_m_y_soucent_02',
    'a_m_y_soucent_03',
    'a_m_y_soucent_04',
    'a_f_m_soucentmc_01',
    'u_m_m_spyactor',
    'u_f_y_spyactress',
    'u_m_y_staggrm_01',
    'a_m_y_stbla_01',
    'a_m_y_stbla_02',
    'ig_stevehains',
    'a_m_m_stlat_02',
    'a_m_y_stlat_01',
    'ig_stretch',
    's_m_m_strperf_01',
    's_m_m_strpreach_01',
    'g_m_y_strpunk_01',
    'g_m_y_strpunk_02',
    's_m_m_strvend_01',
    's_m_y_strvend_01',
    'a_m_y_stwhi_01',
    'a_m_y_stwhi_02',
    'a_m_y_sunbathe_01',
    'a_m_y_surfer_01',
    's_m_y_swat_01',
    's_f_m_sweatshop_01',
    's_f_y_sweatshop_01',
    'ig_talina',
    'ig_tanisha',
    'ig_taocheng',
    'ig_taostranslator',
    'u_m_o_taphillbilly',
    'u_m_y_tattoo_01',
    'a_f_y_tennis_01',
    'a_m_m_tennis_01',
    'ig_tenniscoach',
    'ig_terry',
    'ig_tomepsilon',
    'csb_tonya',
    'ig_tonya',
    'a_f_m_tourist_01',
    'a_f_y_tourist_01',
    'a_f_y_tourist_02',
    'a_m_m_tourist_01',
    'ig_tracydisanto',
    'csb_trafficwarden',
    'ig_trafficwarden',
    'a_f_m_tramp_01',
    'a_m_m_tramp_01',
    'a_m_o_tramp_01',
    'u_m_o_tramp_01',
    'a_f_m_trampbeac_01',
    'a_m_m_trampbeac_01',
    'a_m_m_tranvest_01',
    'a_m_m_tranvest_02',
    's_m_m_trucker_01',
    'ig_tylerdix',
    's_m_m_ups_01',
    's_m_m_ups_02',
    's_m_y_uscg_01',
    'g_f_y_vagos_01',
    's_m_y_valet_01',
    'a_m_y_vindouche_01',
    'a_f_y_vinewood_01',
    'a_f_y_vinewood_02',
    'a_f_y_vinewood_03',
    'a_f_y_vinewood_04',
    'a_m_y_vinewood_01',
    'a_m_y_vinewood_02',
    'a_m_y_vinewood_03',
    'a_m_y_vinewood_04',
    'ig_wade',
    's_m_y_waiter_01',
    'u_m_m_willyfist',
    's_m_y_winclean_01',
    's_m_y_xmech_01',
    'a_f_y_yoga_01',
    'a_m_y_yoga_01',
    'ig_zimbor',
    'u_m_y_prisoner_01',
    'mp_f_boatstaff_01',
    'mp_m_boatstaff_01',
    'ig_chef2',
    'csb_chef2',
    'csb_agent',
    'ig_agent',
    'csb_mp_agent14',
    'ig_mp_agent14',
    'ig_benny',
    's_m_y_blackops_03',
    's_m_m_ccrew_01',
    'ig_karen_daniels',
    'u_m_m_doa_01',
    'u_f_m_drowned_01',
    'u_m_m_edtoh',
    'mp_f_execpa_01',
    'mp_m_execpa_01',
    'a_f_y_femaleagent',
    's_m_m_fibsec_01',
    'u_m_o_filmnoir',
    'ig_g',
    'mp_f_helistaff_01',
    'csb_jackhowitzer',
    'csb_money',
    'ig_money',
    'csb_paige',
    'ig_paige',
    'csb_popov',
    'ig_popov',
    'csb_rashcosvki',
    'ig_rashcosvki',
    'csb_undercover',
    'mp_m_g_vagfun_01',
    'csb_vagspeak',
    'ig_vagspeak',
    'mp_f_chbar_01',
    'mp_f_cocaine_01',
    'mp_f_counterfeit_01',
    'mp_f_forgery_01',
    'mp_f_meth_01',
    'mp_f_weed_01',
    'ig_malc',
    'mp_m_cocaine_01',
    'mp_m_counterfeit_01',
    'mp_m_forgery_01',
    'mp_m_meth_01',
    'mp_m_weed_01',
    's_m_y_xmech_02_mp',
    'mp_f_cardesign_01',
    'g_f_importexport_01',
    'g_m_importexport_01',
    'csb_avon',
    'csb_bogdan',
    'csb_mrs_r',
    'ig_avon',
    'ig_lestercrest_2',
    'mp_f_execpa_02',
    'mp_m_avongoon',
    'mp_m_bogdangoon',
    'mp_m_securoguard_01',
    'mp_m_waremech_01',
    'mp_m_weapexp_01',
    'mp_m_weapwork_01',
    'u_m_y_corpse_01',
    'u_m_y_juggernaut_01',
    'u_m_y_smugmech_01',
    'demogorgon',
    'annabelle',
    'clowngremlins',
    'cthulhu',
    'granny',
    'ryuk',
    'shg',
    'slendrina',
    'tvs',
    'yodaromane',
    'kajou',
    'a_c_pig',
    'ghost_boss',
    'ghost_base'
}

cfg_org.pedListAdmin = {
    'csb_reporter',
    'a_m_o_soucent_02',
    'a_m_o_soucent_03',
    'a_m_o_tramp_01',
    'demogorgon',
    'annabelle',
    'clowngremlins',
    'ryuk',
    'tvs',
    'yodaromane',
    'kajou',
    'a_c_pig',
    'g_m_y_ballaeast_01',
    'g_f_y_ballas_01',
    'TheUndertaker',
    'ReyMysterio',
}