-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------
----------------------------		  Base développer par Extasy#0093		    ---------------------------
----------------------------	    Pour Umbrella PS: (L'anti-Cheat n'est pas	---------------------------
----------------------------		  la. Cherche encore negros🔎😁)		   ---------------------------
-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------

--This empty file causes the scheduler.lua to load clientside
--scheduler.lua when loaded inside the sessionmanager resource currently manages remote callbacks.
--Without this, callbacks will only work server->client and not client->server.